[project]
name = 'Imposter-Syndrome-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.confidence-level-simulator]
path = 'contracts/confidence-level-simulator.clar'
clarity_version = 3
epoch = '3.2'

[contracts.expertise-bluffing-assistant]
path = 'contracts/expertise-bluffing-assistant.clar'
clarity_version = 3
epoch = 'latest'

[contracts.google-search-history-anonymizer]
path = 'contracts/google-search-history-anonymizer.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
